# These are supported funding model platforms

github: [renjujv]
patreon: # Replace with a single patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single ko_fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL