name: Build and push to another branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js with cache
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Gatsby_Build-GHPages_Deploy
      uses: enriikke/gatsby-gh-pages-action@main
      with:
        access-token: ${{ secrets.PAT }}
        gatsby-args: "--"
        deploy-branch: "gh-pages"
